name: Update
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  MANIFEST_PATH: com.github.Lea_fish.Leafish.yaml # Path to manifest
  REPO: # link to project repository (optional)

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub/flatpak-external-data-checker

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update manifest
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        set -x
        git clone -b main https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git main
        cd main
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        /app/flatpak-external-data-checker --update --commit-only ${MANIFEST_PATH}

    - name: Update Rust dependencies
      continue-on-error: true
      run: |
        set -x
        apt-get install -y python3-aiohttp python3-toml
        git clone -b main https://github.com/Lea-fish/Leafish.git leafish
        cd leafish
        git clone https://github.com/flatpak/flatpak-builder-tools.git flatpak-builder-tools
        python3 flatpak-builder-tools/cargo/flatpak-cargo-generator.py Cargo.lock -o ../main/cargo-sources.json
        cd ../main
        git add cargo-sources.json
        git commit -m "Update cargo-sources.json"

    - name: Push to branch
      continue-on-error: true
      run: |
        set -x
        cd main
        git push origin HEAD:main
